# Site settings
author: Makoa DeVincent
title: Makoa's Software Engineering Journey
header-img: img/home-bg.png
email: makoadevincent@gmail.com
copyright_name: Makoa DeVincent
description: > # this means to ignore newlines until "baseurl:"
  My Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MakoaDeVincent

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
